/*
Jenkinsfile new
*/
pipeline {
    agent any
    
    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }
    stages {
        stage('Deploy to Prod ECS'){
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-2'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
        
    }
}